// Enhanced Question data class with translation fields
class Question {
  final int id;
  final String questionText;
  final String questionTranslation;
  final List<String> options;
  final List<String> optionTranslations;
  final int correctAnswerIndex;
  final String questionType;
  final String questionTypeTranslation;
  final String pronunciation;
  final String explanation;
  final String explanationTranslation;

  const Question({
    required this.id,
    required this.questionText,
    this.questionTranslation = "",
    required this.options,
    this.optionTranslations = const [],
    required this.correctAnswerIndex,
    this.questionType = "",
    this.questionTypeTranslation = "",
    this.pronunciation = "",
    this.explanation = "",
    this.explanationTranslation = "",
  });
}

class QuestionRepository {
  // Private constructor for singleton pattern
  QuestionRepository._();

  // Static instance
  static final QuestionRepository _instance = QuestionRepository._();

  // Factory constructor returns the same instance
  factory QuestionRepository() => _instance;

  List<Question> getGermanQuestions() {
    return [
      const Question(
        id: 1,
        questionType: "Zugreisen - Bahnhof",
        questionTypeTranslation: "Train Travel - Train Station",
        questionText: "Was bedeutet 'der Bahnhof'?",
        questionTranslation: "What does 'der Bahnhof' mean?",
        options: ["platform", "train station", "ticket", "departure"],
        optionTranslations: ["[das Gleis]", "[der Bahnhof]", "[die Fahrkarte]", "[die Abfahrt]"],
        correctAnswerIndex: 1,
        pronunciation: "dehr BAHN-hohf",
        explanation: "Der Bahnhof ist der Ort, wo Züge abfahren und ankommen.",
        explanationTranslation: "Der Bahnhof is the place where trains depart and arrive.",
      ),
      const Question(
        id: 2,
        questionType: "Zugreisen - Fahrkarte",
        questionTypeTranslation: "Train Travel - Ticket",
        questionText: "Was bedeutet 'die Fahrkarte'?",
        questionTranslation: "What does 'die Fahrkarte' mean?",
        options: ["timetable", "platform", "ticket", "luggage"],
        optionTranslations: ["[der Fahrplan]", "[das Gleis]", "[die Fahrkarte]", "[das Gepäck]"],
        correctAnswerIndex: 2,
        pronunciation: "dee FAR-kar-tuh",
        explanation: "Die Fahrkarte braucht man, um mit dem Zug zu fahren.",
        explanationTranslation: "You need die Fahrkarte to travel by train.",
      ),
      const Question(
        id: 3,
        questionType: "Zugreisen - Gleis",
        questionTypeTranslation: "Train Travel - Platform",
        questionText: "Was bedeutet 'das Gleis'?",
        questionTranslation: "What does 'das Gleis' mean?",
        options: ["train", "platform", "conductor", "reservation"],
        optionTranslations: ["[der Zug]", "[das Gleis]", "[der Schaffner]", "[die Reservierung]"],
        correctAnswerIndex: 1,
        pronunciation: "dahs GLICE",
        explanation: "Das Gleis ist der Bahnsteig, wo der Zug hält.",
        explanationTranslation: "Das Gleis is the platform where the train stops.",
      ),
      const Question(
        id: 4,
        questionType: "Zugreisen - Abfahrt",
        questionTypeTranslation: "Train Travel - Departure",
        questionText: "Was bedeutet 'die Abfahrt'?",
        questionTranslation: "What does 'die Abfahrt' mean?",
        options: ["arrival", "departure", "delay", "connection"],
        optionTranslations: ["[die Ankunft]", "[die Abfahrt]", "[die Verspätung]", "[der Anschluss]"],
        correctAnswerIndex: 1,
        pronunciation: "dee AHP-fahrt",
        explanation: "Die Abfahrt ist die Zeit, wann der Zug losfährt.",
        explanationTranslation: "Die Abfahrt is the time when the train departs.",
      ),
      const Question(
        id: 5,
        questionType: "Zugreisen - Ankunft",
        questionTypeTranslation: "Train Travel - Arrival",
        questionText: "Was bedeutet 'die Ankunft'?",
        questionTranslation: "What does 'die Ankunft' mean?",
        options: ["departure", "platform", "arrival", "ticket counter"],
        optionTranslations: ["[die Abfahrt]", "[das Gleis]", "[die Ankunft]", "[der Schalter]"],
        correctAnswerIndex: 2,
        pronunciation: "dee AHN-koonft",
        explanation: "Die Ankunft ist die Zeit, wann der Zug am Zielort ankommt.",
        explanationTranslation: "Die Ankunft is the time when the train arrives at the destination.",
      ),
      const Question(
        id: 6,
        questionType: "Zugreisen - Einzelfahrkarte",
        questionTypeTranslation: "Train Travel - One-way Ticket",
        questionText: "Was bedeutet 'die Einzelfahrkarte'?",
        questionTranslation: "What does 'die Einzelfahrkarte' mean?",
        options: ["round-trip ticket", "one-way ticket", "discount ticket", "seat reservation"],
        optionTranslations: ["[die Hin- und Rückfahrkarte]", "[die Einzelfahrkarte]", "[der Sparpreis]", "[die Sitzplatzreservierung]"],
        correctAnswerIndex: 1,
        pronunciation: "dee AYEN-tsel-far-kar-tuh",
        explanation: "Die Einzelfahrkarte ist ein Ticket für eine Fahrt in eine Richtung.",
        explanationTranslation: "Die Einzelfahrkarte is a ticket for a one-way journey.",
      ),
      const Question(
        id: 7,
        questionType: "Zugreisen - Hin- und Rückfahrkarte",
        questionTypeTranslation: "Train Travel - Round-trip Ticket",
        questionText: "Was bedeutet 'die Hin- und Rückfahrkarte'?",
        questionTranslation: "What does 'die Hin- und Rückfahrkarte' mean?",
        options: ["one-way ticket", "round-trip ticket", "platform ticket", "monthly pass"],
        optionTranslations: ["[die Einzelfahrkarte]", "[die Hin- und Rückfahrkarte]", "[die Bahnsteigkarte]", "[die Monatskarte]"],
        correctAnswerIndex: 1,
        pronunciation: "dee HIN oont ROOK-far-kar-tuh",
        explanation: "Die Hin- und Rückfahrkarte ist ein Ticket für eine Reise mit Rückkehr.",
        explanationTranslation: "Die Hin- und Rückfahrkarte is a ticket for a journey with return.",
      ),
      const Question(
        id: 8,
        questionType: "Zugreisen - Reservierung",
        questionTypeTranslation: "Train Travel - Reservation",
        questionText: "Was bedeutet 'die Reservierung'?",
        questionTranslation: "What does 'die Reservierung' mean?",
        options: ["delay", "reservation", "luggage", "conductor"],
        optionTranslations: ["[die Verspätung]", "[die Reservierung]", "[das Gepäck]", "[der Schaffner]"],
        correctAnswerIndex: 1,
        pronunciation: "dee reh-zer-VEE-roong",
        explanation: "Die Reservierung garantiert einen bestimmten Sitzplatz im Zug.",
        explanationTranslation: "Die Reservierung guarantees a specific seat on the train.",
      ),
      const Question(
        id: 9,
        questionType: "Zugreisen - ICE (Intercity Express)",
        questionTypeTranslation: "Train Travel - ICE (High-Speed Train)",
        questionText: "Was ist der ICE?",
        questionTranslation: "What is the ICE?",
        options: ["regional train", "high-speed train", "tram", "bus"],
        optionTranslations: ["[der Regionalzug]", "[der Hochgeschwindigkeitszug]", "[die Straßenbahn]", "[der Bus]"],
        correctAnswerIndex: 1,
        pronunciation: "ee-tseh-EH",
        explanation: "ICE steht für Intercity-Express und ist der schnellste Zug in Deutschland.",
        explanationTranslation: "ICE stands for Intercity-Express and is the fastest train in Germany.",
      ),
      const Question(
        id: 10,
        questionType: "Zugreisen - Umsteigen",
        questionTypeTranslation: "Train Travel - Transfer",
        questionText: "Was bedeutet 'umsteigen'?",
        questionTranslation: "What does 'umsteigen' mean?",
        options: ["to board", "to transfer", "to validate", "to delay"],
        optionTranslations: ["[einsteigen]", "[umsteigen]", "[entwerten]", "[verspäten]"],
        correctAnswerIndex: 1,
        pronunciation: "OOM-shty-gen",
        explanation: "Umsteigen bedeutet, von einem Zug in einen anderen zu wechseln.",
        explanationTranslation: "Umsteigen means to change from one train to another.",
      ),
      const Question(
        id: 11,
        questionType: "Zugreisen - Verspätung",
        questionTypeTranslation: "Train Travel - Delay",
        questionText: "Was bedeutet 'die Verspätung'?",
        questionTranslation: "What does 'die Verspätung' mean?",
        options: ["departure", "delay", "arrival", "connection"],
        optionTranslations: ["[die Abfahrt]", "[die Verspätung]", "[die Ankunft]", "[der Anschluss]"],
        correctAnswerIndex: 1,
        pronunciation: "dee fehr-SHPAY-toong",
        explanation: "Die Verspätung bedeutet, dass der Zug nicht pünktlich ist.",
        explanationTranslation: "Die Verspätung means that the train is not on time.",
      ),
      const Question(
        id: 12,
        questionType: "Zugreisen - Schaffner",
        questionTypeTranslation: "Train Travel - Conductor",
        questionText: "Was bedeutet 'der Schaffner'?",
        questionTranslation: "What does 'der Schaffner' mean?",
        options: ["platform", "conductor", "passenger", "ticket machine"],
        optionTranslations: ["[der Bahnsteig]", "[der Schaffner]", "[der Fahrgast]", "[der Fahrkartenautomat]"],
        correctAnswerIndex: 1,
        pronunciation: "dehr SHAHF-nehr",
        explanation: "Der Schaffner kontrolliert die Fahrkarten im Zug.",
        explanationTranslation: "Der Schaffner checks tickets on the train.",
      ),
      const Question(
        id: 13,
        questionType: "Zugreisen - Gepäckablage",
        questionTypeTranslation: "Train Travel - Luggage Rack",
        questionText: "Was bedeutet 'die Gepäckablage'?",
        questionTranslation: "What does 'die Gepäckablage' mean?",
        options: ["luggage rack", "seat", "dining car", "toilet"],
        optionTranslations: ["[die Gepäckablage]", "[der Sitzplatz]", "[der Speisewagen]", "[die Toilette]"],
        correctAnswerIndex: 0,
        pronunciation: "dee geh-PECK-ahp-lah-guh",
        explanation: "Die Gepäckablage ist der Ort im Zug, wo man sein Gepäck abstellt.",
        explanationTranslation: "Die Gepäckablage is the place on the train where you store your luggage.",
      ),
      const Question(
        id: 14,
        questionType: "Zugreisen - Fahrplan",
        questionTypeTranslation: "Train Travel - Timetable",
        questionText: "Was bedeutet 'der Fahrplan'?",
        questionTranslation: "What does 'der Fahrplan' mean?",
        options: ["platform", "ticket", "timetable", "train car"],
        optionTranslations: ["[das Gleis]", "[die Fahrkarte]", "[der Fahrplan]", "[der Wagen]"],
        correctAnswerIndex: 2,
        pronunciation: "dehr FAR-plahn",
        explanation: "Der Fahrplan zeigt die Abfahrts- und Ankunftszeiten der Züge.",
        explanationTranslation: "Der Fahrplan shows the departure and arrival times of trains.",
      ),
      const Question(
        id: 15,
        questionType: "Zugreisen - Speisewagen",
        questionTypeTranslation: "Train Travel - Dining Car",
        questionText: "Was bedeutet 'der Speisewagen'?",
        questionTranslation: "What does 'der Speisewagen' mean?",
        options: ["dining car", "luggage car", "sleeping car", "passenger car"],
        optionTranslations: ["[der Speisewagen]", "[der Gepäckwagen]", "[der Schlafwagen]", "[der Personenwagen]"],
        correctAnswerIndex: 0,
        pronunciation: "dehr SHPY-zuh-vah-gen",
        explanation: "Der Speisewagen ist ein Zugabteil, wo man Essen und Trinken kaufen kann.",
        explanationTranslation: "Der Speisewagen is a train compartment where you can buy food and drinks.",
      ),
      const Question(
        id: 16,
        questionType: "Zugreisen - Schalter",
        questionTypeTranslation: "Train Travel - Ticket Counter",
        questionText: "Was bedeutet 'der Schalter'?",
        questionTranslation: "What does 'der Schalter' mean?",
        options: ["platform", "ticket counter", "train", "seat"],
        optionTranslations: ["[der Bahnsteig]", "[der Schalter]", "[der Zug]", "[der Platz]"],
        correctAnswerIndex: 1,
        pronunciation: "dehr SHAHL-tehr",
        explanation: "Am Schalter kann man Fahrkarten kaufen und Informationen bekommen.",
        explanationTranslation: "At the Schalter you can buy tickets and get information.",
      ),
      const Question(
        id: 17,
        questionType: "Zugreisen - Phrase: Wo ist...?",
        questionTypeTranslation: "Train Travel - Phrase: Where is...?",
        questionText: "Wie fragt man 'Where can I buy a ticket?'",
        questionTranslation: "How do you ask 'Where can I buy a ticket?'",
        options: ["Wann fährt der Zug?", "Wo kann ich ein Ticket kaufen?", "Wie viel kostet das?", "Welches Gleis?"],
        optionTranslations: ["[When does the train leave?]", "[Where can I buy a ticket?]", "[How much does it cost?]", "[Which platform?]"],
        correctAnswerIndex: 1,
        pronunciation: "voh kahn ikh ayen TIH-ket KOW-fen",
        explanation: "Diese Frage hilft, den Ort zu finden, wo man Fahrkarten kauft.",
        explanationTranslation: "This question helps to find the place where you buy tickets.",
      ),
      const Question(
        id: 18,
        questionType: "Zugreisen - Phrase: Ist dieser Platz frei?",
        questionTypeTranslation: "Train Travel - Phrase: Is this seat free?",
        questionText: "Was bedeutet 'Ist dieser Platz frei?'",
        questionTranslation: "What does 'Ist dieser Platz frei?' mean?",
        options: ["Where is my seat?", "Is this seat free?", "Can I reserve a seat?", "Which car is this?"],
        optionTranslations: ["[Wo ist mein Platz?]", "[Ist dieser Platz frei?]", "[Kann ich einen Platz reservieren?]", "[Welcher Wagen ist das?]"],
        correctAnswerIndex: 1,
        pronunciation: "ist DEE-zehr plahts fry",
        explanation: "Man stellt diese Frage, bevor man sich im Zug hinsetzt.",
        explanationTranslation: "You ask this question before sitting down on the train.",
      ),
      const Question(
        id: 19,
        questionType: "Zugreisen - Phrase: Hält dieser Zug in...?",
        questionTypeTranslation: "Train Travel - Phrase: Does this train stop in...?",
        questionText: "Was fragt man mit 'Hält dieser Zug in Berlin?'",
        questionTranslation: "What are you asking with 'Hält dieser Zug in Berlin?'",
        options: ["When does the train leave for Berlin?", "Does this train stop in Berlin?", "Where is the train to Berlin?", "How long to Berlin?"],
        optionTranslations: ["[Wann fährt der Zug nach Berlin?]", "[Hält dieser Zug in Berlin?]", "[Wo ist der Zug nach Berlin?]", "[Wie lange nach Berlin?]"],
        correctAnswerIndex: 1,
        pronunciation: "helt DEE-zehr tsoog in behr-LEEN",
        explanation: "Diese Frage hilft zu wissen, ob der Zug am gewünschten Ort hält.",
        explanationTranslation: "This question helps to know if the train stops at the desired location.",
      ),
      const Question(
        id: 20,
        questionType: "Zugreisen - Phrase: Einmal nach..., bitte",
        questionTypeTranslation: "Train Travel - Phrase: One ticket to..., please",
        questionText: "Was bedeutet 'Einmal nach München, bitte'?",
        questionTranslation: "What does 'Einmal nach München, bitte' mean?",
        options: ["Two tickets to Munich, please", "One ticket to Munich, please", "Return to Munich, please", "When to Munich, please"],
        optionTranslations: ["[Zweimal nach München, bitte]", "[Einmal nach München, bitte]", "[Rückfahrt nach München, bitte]", "[Wann nach München, bitte]"],
        correctAnswerIndex: 1,
        pronunciation: "AYEN-mahl nahkh MOON-khen BIT-tuh",
        explanation: "So bestellt man eine einfache Fahrkarte am Schalter.",
        explanationTranslation: "This is how you order a one-way ticket at the counter.",
      ),
    ];
  }

  // Backward compatibility
  List<Question> getQuestions() {
    return getGermanQuestions();
  }
}
