class Question {
  final int id;
  final String questionText;
  final String questionTranslation;
  final List<String> options;
  final List<String> optionTranslations;
  final int correctAnswerIndex;
  final String questionType;
  final String questionTypeTranslation;
  final String pronunciation;
  final String explanation;
  final String explanationTranslation;

  const Question({
    required this.id,
    required this.questionText,
    this.questionTranslation = "",
    required this.options,
    this.optionTranslations = const [],
    required this.correctAnswerIndex,
    this.questionType = "",
    this.questionTypeTranslation = "",
    this.pronunciation = "",
    this.explanation = "",
    this.explanationTranslation = "",
  });
}

class QuestionRepository {
  // Private constructor for singleton pattern
  QuestionRepository._();

  // Static instance
  static final QuestionRepository _instance = QuestionRepository._();

  // Factory constructor to return the singleton instance
  factory QuestionRepository() => _instance;

  List<Question> getGermanQuestions() {
    return [
      const Question(
        id: 1,
        questionType: "Einstieg",
        questionTypeTranslation: "Getting Started",
        questionText: "[translate:Woher kommt Amir?]",
        questionTranslation: "Where does Amir come from?",
        options: ["[translate:Deutschland]", "[translate:Marokko]", "[translate:Frankreich]", "[translate:Spanien]"],
        optionTranslations: ["Germany", "Morocco", "France", "Spain"],
        correctAnswerIndex: 1,
        pronunciation: "mah-roh-koh",
        explanation: "[translate:Amir kommt aus Marokko.]",
        explanationTranslation: "Amir comes from Morocco.",
      ),
      const Question(
        id: 2,
        questionType: "Verkehr",
        questionTypeTranslation: "Transport",
        questionText: "[translate:Wie kann man ein Zugticket kaufen, wenn der Automat kaputt ist?]",
        questionTranslation: "How can you buy a train ticket if the machine is broken?",
        options: ["[translate:Im Laden]", "[translate:Online]", "[translate:Beim Fahrer]", "[translate:Gar nicht]"],
        optionTranslations: ["In store", "Online", "From the driver", "Not at all"],
        correctAnswerIndex: 1,
        pronunciation: "on-line",
        explanation: "[translate:Tickets kann man auch online kaufen.]",
        explanationTranslation: "Tickets can also be bought online.",
      ),
      const Question(
        id: 3,
        questionType: "Verkehr",
        questionTypeTranslation: "Transport",
        questionText: "[translate:Was bedeutet die Rolltreppenregel?]",
        questionTranslation: "What does the escalator rule mean?",
        options: ["[translate:Links stehen, rechts gehen]", "[translate:Rechts stehen, links gehen]", "[translate:In der Mitte stehen]", "[translate:Sich nicht festhalten]"],
        optionTranslations: ["Stand left, walk right", "Stand right, walk left", "Stand in the middle", "Don't hold on"],
        correctAnswerIndex: 1,
        pronunciation: "roll-trep-pen",
        explanation: "[translate:Die Rolltreppenregel ist: Rechts stehen, links gehen.]",
        explanationTranslation: "The escalator rule is: stand right, walk left.",
      ),
      const Question(
        id: 4,
        questionType: "Verkehr",
        questionTypeTranslation: "Transport",
        questionText: "[translate:Was kostet ein Monatsticket für Auszubildende?]",
        questionTranslation: "What does a monthly ticket for trainees cost?",
        options: ["[translate:Besonders günstig]", "[translate:Teuer]", "[translate:Gleich wie andere]", "[translate:Nicht verfügbar]"],
        optionTranslations: ["Especially cheap", "Expensive", "Same as others", "Not available"],
        correctAnswerIndex: 0,
        pronunciation: "monats-tik-et",
        explanation: "[translate:Monatstickets für Auszubildende sind günstig.]",
        explanationTranslation: "Monthly tickets for trainees are cheap.",
      ),
      const Question(
        id: 5,
        questionType: "Sozial",
        questionTypeTranslation: "Social",
        questionText: "[translate:Was macht Amir am ersten Tag in Deutschland?]",
        questionTranslation: "What does Amir do on his first day in Germany?",
        options: ["[translate:Sucht Wohnung]", "[translate:Kauft Ticket]", "[translate:Geht zur Arbeit]", "[translate:Nichts]"],
        optionTranslations: ["Looks for apartment", "Buys ticket", "Goes to work", "Nothing"],
        correctAnswerIndex: 1,
        pronunciation: "tik-et",
        explanation: "[translate:Amir lernt, ein Ticket zu kaufen.]",
        explanationTranslation: "Amir learns to buy a ticket.",
      ),
      const Question(
        id: 6,
        questionType: "Sprachgebrauch",
        questionTypeTranslation: "Language Use",
        questionText: "[translate:Was sagt man, wenn man jemanden um Hilfe bittet?]",
        questionTranslation: "What do you say when you ask someone for help?",
        options: ["[translate:Entschuldigung]", "[translate:Danke]", "[translate:Hallo]", "[translate:Auf Wiedersehen]"],
        optionTranslations: ["Excuse me", "Thank you", "Hello", "Goodbye"],
        correctAnswerIndex: 0,
        pronunciation: "ent-shool-dee-goong",
        explanation: "[translate:Entschuldigung wird für Bitten benutzt.]",
        explanationTranslation: "Excuse me is used for requests.",
      ),
      const Question(
        id: 7,
        questionType: "Verkehr",
        questionTypeTranslation: "Transport",
        questionText: "[translate:Wie findet Amir den richtigen Bus?]",
        questionTranslation: "How does Amir find the right bus?",
        options: ["[translate:Fragt Menschen]", "[translate:Sieht auf Fahrplan]", "[translate:Wartet]", "[translate:Nimmt Taxi]"],
        optionTranslations: ["Asks people", "Looks at timetable", "Waits", "Takes taxi"],
        correctAnswerIndex: 0,
        pronunciation: "fraa-gt men-shen",
        explanation: "[translate:Freundliche Menschen helfen Amir.]",
        explanationTranslation: "Friendly people help Amir.",
      ),
      const Question(
        id: 8,
        questionType: "Zahlen",
        questionTypeTranslation: "Numbers",
        questionText: "[translate:Wie viele Stationen kosten weniger als ein Flughafen-Ticket?]",
        questionTranslation: "How many stations cost less than an airport ticket?",
        options: ["[translate:1-2 Stationen]", "[translate:3-4 Stationen]", "[translate:5-6 Stationen]", "[translate:Alle Stationen]"],
        optionTranslations: ["1-2 stations", "3-4 stations", "5-6 stations", "All stations"],
        correctAnswerIndex: 0,
        pronunciation: "sh-tah-tsi-oh-nen",
        explanation: "[translate:Tarife für 1-2 Stationen sind günstiger.]",
        explanationTranslation: "Tariffs for 1-2 stations are cheaper.",
      ),
      const Question(
        id: 9,
        questionType: "Verkehr",
        questionTypeTranslation: "Transport",
        questionText: "[translate:Warum ist das Taxi teurer als ein Zugticket?]",
        questionTranslation: "Why is the taxi more expensive than a train ticket?",
        options: ["[translate:Weil es schneller ist]", "[translate:Weil es bequemer ist]", "[translate:Weil es private Dienste sind]", "[translate:Weil es mehr kostet]"],
        optionTranslations: ["Because it is faster", "Because it is more comfortable", "Because it is private service", "Because it costs more"],
        correctAnswerIndex: 3,
        pronunciation: "tew-ree-ur",
        explanation: "[translate:Taxi kostet mehr als Zugticket.]",
        explanationTranslation: "Taxi costs more than train ticket.",
      ),
      const Question(
        id: 10,
        questionType: "Sozial",
        questionTypeTranslation: "Social",
        questionText: "[translate:Wie fühlt sich Amir am ersten Tag in Deutschland?]",
        questionTranslation: "How does Amir feel on his first day in Germany?",
        options: ["[translate:Glücklich]", "[translate:Nervös]", "[translate:Traurig]", "[translate:Wütend]"],
        optionTranslations: ["Happy", "Nervous", "Sad", "Angry"],
        correctAnswerIndex: 1,
        pronunciation: "ner-vuhs",
        explanation: "[translate:Amir ist nervös am ersten Tag.]",
        explanationTranslation: "Amir is nervous on first day.",
      ),
      const Question(
        id: 11,
        questionType: "Verkehr",
        questionTypeTranslation: "Transport",
        questionText: "[translate:Was ist der Vorteil eines Monatstickets?]",
        questionTranslation: "What is the advantage of a monthly ticket?",
        options: ["[translate:Es ist billiger]", "[translate:Es ist teurer]", "[translate:Es ist nur für Studenten]", "[translate:Es ist ungültig]"],
        optionTranslations: ["It is cheaper", "It is more expensive", "Only for students", "It is invalid"],
        correctAnswerIndex: 0,
        pronunciation: "bil-lee-gur",
        explanation: "[translate:Monatstickets sind günstiger.]",
        explanationTranslation: "Monthly tickets are cheaper.",
      ),
      const Question(
        id: 12,
        questionType: "Sozial",
        questionTypeTranslation: "Social",
        questionText: "[translate:Wie begrüßt man jemanden in Deutschland?]",
        questionTranslation: "How do you greet someone in Germany?",
        options: ["[translate:Tschüss]", "[translate:Hallo]", "[translate:Guten Morgen]", "[translate:Auf Wiedersehen]"],
        optionTranslations: ["Bye", "Hello", "Good morning", "Goodbye"],
        correctAnswerIndex: 1,
        pronunciation: "hah-lo",
        explanation: "[translate:Hallo ist die gebräuchliche Begrüßung.]",
        explanationTranslation: "Hallo is the common greeting.",
      ),
      const Question(
        id: 13,
        questionType: "Fragen",
        questionTypeTranslation: "Questions",
        questionText: "[translate:Wie fragt man, wo der Bus ist?]",
        questionTranslation: "How do you ask where the bus is?",
        options: ["[translate:Wo ist der Bus?]", "[translate:Was ist der Bus?]", "[translate:Wie ist der Bus?]", "[translate:Warum ist der Bus?]"],
        optionTranslations: ["Where is the bus?", "What is the bus?", "How is the bus?", "Why is the bus?"],
        correctAnswerIndex: 0,
        pronunciation: "voh",
        explanation: "[translate:Wo fragt man nach Standort.]",
        explanationTranslation: "Where asks for location.",
      ),
      const Question(
        id: 14,
        questionType: "Zeit",
        questionTypeTranslation: "Time",
        questionText: "[translate:Was bedeutet 'Heute'?]",
        questionTranslation: "What does 'Heute' mean?",
        options: ["[translate:Gestern]", "[translate:Heute]", "[translate:Morgen]", "[translate:Nacht]"],
        optionTranslations: ["Yesterday", "Today", "Tomorrow", "Night"],
        correctAnswerIndex: 1,
        pronunciation: "hoy-tuh",
        explanation: "[translate:Heute bedeutet der heutige Tag.]",
        explanationTranslation: "Heute means the current day.",
      ),
      const Question(
        id: 15,
        questionType: "Verkehr",
        questionTypeTranslation: "Transport",
        questionText: "[translate:Was macht man, wenn der Automat kaputt ist?]",
        questionTranslation: "What do you do if the machine is broken?",
        options: ["[translate:Warten]", "[translate:Online kaufen]", "[translate:Zurückgehen]", "[translate:Nicht fahren]"],
        optionTranslations: ["Wait", "Buy online", "Go back", "Don't travel"],
        correctAnswerIndex: 1,
        pronunciation: "on-line kown-fen",
        explanation: "[translate:Tickets kann man online kaufen.]",
        explanationTranslation: "Tickets can be bought online.",
      ),
      const Question(
        id: 16,
        questionType: "Sozial",
        questionTypeTranslation: "Social",
        questionText: "[translate:Wie sagt man 'Entschuldigung' auf Englisch?]",
        questionTranslation: "How do you say 'Entschuldigung' in English?",
        options: ["[translate:Excuse me]", "[translate:Thank you]", "[translate:Hello]", "[translate:Sorry]"],
        optionTranslations: ["Excuse me", "Thank you", "Hello", "Sorry"],
        correctAnswerIndex: 0,
        pronunciation: "ent-shool-dee-goong",
        explanation: "[translate:Entschuldigung bedeutet um Hilfe bitten.]",
        explanationTranslation: "Entschuldigung means to ask for help.",
      ),
      const Question(
        id: 17,
        questionType: "Wegbeschreibung",
        questionTypeTranslation: "Directions",
        questionText: "[translate:Wie sagt man, man sucht den Weg?]",
        questionTranslation: "How do you say you are looking for the way?",
        options: ["[translate:Ich suche den Weg]", "[translate:Ich finde den Weg]", "[translate:Ich gehe den Weg]", "[translate:Ich kenne den Weg]"],
        optionTranslations: ["I am looking for the way", "I find the way", "I am going the way", "I know the way"],
        correctAnswerIndex: 0,
        pronunciation: "soo-huh",
        explanation: "[translate:Ich suche den Weg bedeutet Weg finden.]",
        explanationTranslation: "I am looking for the way means to find the way.",
      ),
      const Question(
        id: 18,
        questionType: "Sozial",
        questionTypeTranslation: "Social",
        questionText: "[translate:Was soll man tun, wenn man den Akku leer hat?]",
        questionTranslation: "What should you do when your battery is empty?",
        options: ["[translate:Nach Hilfe fragen]", "[translate:Warten]", "[translate:Sich ärgern]", "[translate:Suchen]"],
        optionTranslations: ["Ask for help", "Wait", "Get angry", "Search"],
        correctAnswerIndex: 0,
        pronunciation: "ah-koo",
        explanation: "[translate:Man soll nach Hilfe fragen.]",
        explanationTranslation: "One should ask for help.",
      ),
      const Question(
        id: 19,
        questionType: "Verkehr",
        questionTypeTranslation: "Transport",
        questionText: "[translate:Warum sind öffentliche Verkehrsmittel wichtig?]",
        questionTranslation: "Why is public transport important?",
        options: ["[translate:Weil sie billig ist]", "[translate:Weil sie viele Leute bringt]", "[translate:Weil sie umweltfreundlich ist]", "[translate:Weil sie schnell ist]"],
        optionTranslations: ["Because it is cheap", "Because it brings many people", "Because it is environmentally friendly", "Because it is fast"],
        correctAnswerIndex: 2,
        pronunciation: "um-velt-freun-dlish",
        explanation: "[translate:Öffentliche Verkehrsmittel sind umweltfreundlich.]",
        explanationTranslation: "Public transport is environmentally friendly.",
      ),
      const Question(
        id: 20,
        questionType: "Sozial",
        questionTypeTranslation: "Social",
        questionText: "[translate:Was macht man, wenn der Akku leer ist?]",
        questionTranslation: "What do you do when the battery is empty?",
        options: ["[translate:Nach Hilfe fragen]", "[translate:Warten]", "[translate:Versuchen aufzuladen]", "[translate:Sich ärgern]"],
        optionTranslations: ["Ask for help", "Wait", "Try to charge", "Get angry"],
        correctAnswerIndex: 2,
        pronunciation: "ah-koo",
        explanation: "[translate:Man versucht, das Gerät aufzuladen.]",
        explanationTranslation: "One tries to charge the device.",
      ),
    ];
  }

  // Backward compatibility
  List<Question> getQuestions() {
    return getGermanQuestions();
  }
}
