// Enhanced Question data class with translation and audio fields
class Question {
  final int id;
  final String questionText;
  final String questionTranslation;
  final List<String> options;
  final List<String> optionTranslations;
  final int correctAnswerIndex;
  final String questionType;
  final String questionTypeTranslation;
  final String pronunciation;
  final String explanation;
  final String explanationTranslation;
  // New field for Text-to-Speech engine
  final String audioPhrase;

  const Question({
    required this.id,
    required this.questionText,
    this.questionTranslation = "",
    required this.options,
    this.optionTranslations = const [],
    required this.correctAnswerIndex,
    this.questionType = "",
    this.questionTypeTranslation = "",
    this.pronunciation = "",
    this.explanation = "",
    this.explanationTranslation = "",
    this.audioPhrase = "",
  });
}

class QuestionRepository {
  // Private constructor for singleton pattern
  QuestionRepository._();

  // Static instance
  static final QuestionRepository _instance = QuestionRepository._();

  // Factory constructor returns the same instance
  factory QuestionRepository() => _instance;

  List<Question> getItalianQuestions() {
    return [
      const Question(
        id: 1,
        questionType: "Train Travel - Station",
        questionTypeTranslation: "Train Travel - Station",
        questionText: "What does 'la stazione ferroviaria' mean?",
        questionTranslation: "What does 'la stazione ferroviaria' mean?",
        options: ["platform", "train station", "ticket", "departure"],
        optionTranslations: ["il binario", "la stazione ferroviaria", "il biglietto", "la partenza"],
        correctAnswerIndex: 1,
        pronunciation: "la sta-TSIO-ne fer-ro-via-RIA",
        explanation: "The train station is the place where trains depart and arrive.",
        explanationTranslation: "The train station is the place where trains depart and arrive.",
        audioPhrase: "la stazione ferroviaria",
      ),
      const Question(
        id: 2,
        questionType: "Train Travel - Ticket",
        questionTypeTranslation: "Train Travel - Ticket",
        questionText: "What does 'il biglietto' mean?",
        questionTranslation: "What does 'il biglietto' mean?",
        options: ["timetable", "platform", "ticket", "luggage"],
        optionTranslations: ["l'orario", "il binario", "il biglietto", "il bagaglio"],
        correctAnswerIndex: 2,
        pronunciation: "il bi-GLIET-to",
        explanation: "You need a ticket to travel by train.",
        explanationTranslation: "You need a ticket to travel by train.",
        audioPhrase: "il biglietto",
      ),
      const Question(
        id: 3,
        questionType: "Train Travel - Platform",
        questionTypeTranslation: "Train Travel - Platform",
        questionText: "What does 'il binario' mean?",
        questionTranslation: "What does 'il binario' mean?",
        options: ["train", "platform", "conductor", "reservation"],
        optionTranslations: ["il treno", "il binario", "il controllore", "la prenotazione"],
        correctAnswerIndex: 1,
        pronunciation: "il bi-NA-rio",
        explanation: "The platform is where the train stops.",
        explanationTranslation: "The platform is where the train stops.",
        audioPhrase: "il binario",
      ),
      const Question(
        id: 4,
        questionType: "Train Travel - Departure",
        questionTypeTranslation: "Train Travel - Departure",
        questionText: "What does 'la partenza' mean?",
        questionTranslation: "What does 'la partenza' mean?",
        options: ["arrival", "departure", "delay", "connection"],
        optionTranslations: ["l'arrivo", "la partenza", "il ritardo", "la coincidenza"],
        correctAnswerIndex: 1,
        pronunciation: "la par-TEN-za",
        explanation: "The departure is the time when the train leaves the station.",
        explanationTranslation: "The departure is the time when the train leaves the station.",
        audioPhrase: "la partenza",
      ),
      const Question(
        id: 5,
        questionType: "Train Travel - Arrival",
        questionTypeTranslation: "Train Travel - Arrival",
        questionText: "What does 'l'arrivo' mean?",
        questionTranslation: "What does 'l'arrivo' mean?",
        options: ["departure", "platform", "arrival", "ticket counter"],
        optionTranslations: ["la partenza", "il binario", "l'arrivo", "la biglietteria"],
        correctAnswerIndex: 2,
        pronunciation: "lar-RI-vo",
        explanation: "The arrival is the time when the train arrives at the destination.",
        explanationTranslation: "The arrival is the time when the train arrives at the destination.",
        audioPhrase: "l'arrivo",
      ),
      const Question(
        id: 6,
        questionType: "Train Travel - Round Trip",
        questionTypeTranslation: "Train Travel - Round Trip",
        questionText: "What does 'andata e ritorno' mean?",
        questionTranslation: "What does 'andata e ritorno' mean?",
        options: ["one-way ticket", "round trip", "discount ticket", "seat reservation"],
        optionTranslations: ["biglietto di sola andata", "andata e ritorno", "biglietto scontato", "prenotazione del posto"],
        correctAnswerIndex: 1,
        pronunciation: "an-DA-ta e ri-TOR-no",
        explanation: "A round-trip ticket includes both departure and return journeys.",
        explanationTranslation: "A round-trip ticket includes both departure and return journeys.",
        audioPhrase: "andata e ritorno",
      ),
      const Question(
        id: 7,
        questionType: "Train Travel - Schedule",
        questionTypeTranslation: "Train Travel - Schedule",
        questionText: "What does 'l'orario' mean?",
        questionTranslation: "What does 'l'orario' mean?",
        options: ["platform", "ticket", "timetable", "train car"],
        optionTranslations: ["il binario", "il biglietto", "l'orario", "la carrozza"],
        correctAnswerIndex: 2,
        pronunciation: "lo-RA-rio",
        explanation: "The timetable shows the departure and arrival times of trains.",
        explanationTranslation: "The timetable shows the departure and arrival times of trains.",
        audioPhrase: "l'orario",
      ),
      const Question(
        id: 8,
        questionType: "Train Travel - Delay",
        questionTypeTranslation: "Train Travel - Delay",
        questionText: "What does 'il ritardo' mean?",
        questionTranslation: "What does 'il ritardo' mean?",
        options: ["departure", "delay", "arrival", "cancellation"],
        optionTranslations: ["la partenza", "il ritardo", "l'arrivo", "la cancellazione"],
        correctAnswerIndex: 1,
        pronunciation: "il ri-TAR-do",
        explanation: "A delay means that the train is not on time.",
        explanationTranslation: "A delay means that the train is not on time.",
        audioPhrase: "il ritardo",
      ),
      const Question(
        id: 9,
        questionType: "Train Travel - Train Car",
        questionTypeTranslation: "Train Travel - Train Car",
        questionText: "What does 'la carrozza' mean?",
        questionTranslation: "What does 'la carrozza' mean?",
        options: ["platform", "train car", "ticket office", "luggage"],
        optionTranslations: ["il binario", "la carrozza", "la biglietteria", "il bagaglio"],
        correctAnswerIndex: 1,
        pronunciation: "la car-ROZ-za",
        explanation: "A train car is one section or compartment of the train.",
        explanationTranslation: "A train car is one section or compartment of the train.",
        audioPhrase: "la carrozza",
      ),
      const Question(
        id: 10,
        questionType: "Train Travel - Ticket Office",
        questionTypeTranslation: "Train Travel - Ticket Office",
        questionText: "What does 'la biglietteria' mean?",
        questionTranslation: "What does 'la biglietteria' mean?",
        options: ["platform", "ticket office", "train", "seat"],
        optionTranslations: ["il binario", "la biglietteria", "il treno", "il posto"],
        correctAnswerIndex: 1,
        pronunciation: "la bi-gliet-te-RI-a",
        explanation: "At the ticket office you can buy tickets and get information.",
        explanationTranslation: "At the ticket office you can buy tickets and get information.",
        audioPhrase: "la biglietteria",
      ),
      const Question(
        id: 11,
        questionType: "Common Phrases - Buying Tickets",
        questionTypeTranslation: "Common Phrases - Buying Tickets",
        questionText: "How do you say 'Where can I buy tickets?'",
        questionTranslation: "How do you say 'Where can I buy tickets?'",
        options: ["Quando parte il treno?", "Dove posso comprare i biglietti?", "Quanto costa?", "Quale binario?"],
        optionTranslations: ["When does the train leave?", "Where can I buy tickets?", "How much does it cost?", "Which platform?"],
        correctAnswerIndex: 1,
        pronunciation: "DO-ve POS-so com-PRA-re i bi-GLIET-ti",
        explanation: "This question helps you find where to purchase train tickets.",
        explanationTranslation: "This question helps you find where to purchase train tickets.",
        audioPhrase: "Dove posso comprare i biglietti?",
      ),
      const Question(
        id: 12,
        questionType: "Common Phrases - Requesting Ticket",
        questionTypeTranslation: "Common Phrases - Requesting Ticket",
        questionText: "How do you say 'A ticket to Rome, please'?",
        questionTranslation: "How do you say 'A ticket to Rome, please'?",
        options: ["Due biglietti per Roma", "Un biglietto per Roma, per favore", "Ritorno a Roma", "Quando per Roma"],
        optionTranslations: ["Two tickets to Rome", "A ticket to Rome, please", "Return to Rome", "When to Rome"],
        correctAnswerIndex: 1,
        pronunciation: "un bi-GLIET-to per RO-ma, per fa-VO-re",
        explanation: "This is how you order a ticket at the counter politely.",
        explanationTranslation: "This is how you order a ticket at the counter politely.",
        audioPhrase: "Un biglietto per Roma, per favore",
      ),
      const Question(
        id: 13,
        questionType: "Common Phrases - Train Timing",
        questionTypeTranslation: "Common Phrases - Train Timing",
        questionText: "How do you ask 'What time does the train leave?'",
        questionTranslation: "How do you ask 'What time does the train leave?'",
        options: ["Dove va il treno?", "A che ora parte il treno?", "Quale treno?", "Chi parte?"],
        optionTranslations: ["Where does the train go?", "What time does the train leave?", "Which train?", "Who leaves?"],
        correctAnswerIndex: 1,
        pronunciation: "a ke O-ra PAR-te il TRE-no",
        explanation: "Use this phrase to ask about departure times.",
        explanationTranslation: "Use this phrase to ask about departure times.",
        audioPhrase: "A che ora parte il treno?",
      ),
      const Question(
        id: 14,
        questionType: "Common Phrases - Platform Information",
        questionTypeTranslation: "Common Phrases - Platform Information",
        questionText: "How do you ask 'Which platform for the train to Milan?'",
        questionTranslation: "How do you ask 'Which platform for the train to Milan?'",
        options: ["Dove è Milano?", "Quale binario per il treno per Milano?", "Quanto costa Milano?", "Chi va a Milano?"],
        optionTranslations: ["Where is Milan?", "Which platform for the train to Milan?", "How much is Milan?", "Who goes to Milan?"],
        correctAnswerIndex: 1,
        pronunciation: "KWA-le bi-NA-rio per il TRE-no per mi-LA-no",
        explanation: "This question helps you find the correct platform for your train.",
        explanationTranslation: "This question helps you find the correct platform for your train.",
        audioPhrase: "Quale binario per il treno per Milano?",
      ),
      const Question(
        id: 15,
        questionType: "Common Phrases - Train Stops",
        questionTypeTranslation: "Common Phrases - Train Stops",
        questionText: "How do you ask 'Does this train stop at Florence?'",
        questionTranslation: "How do you ask 'Does this train stop at Florence?'",
        options: ["Quando arriva a Firenze?", "Questo treno si ferma a Firenze?", "Dove è Firenze?", "Quanto per Firenze?"],
        optionTranslations: ["When does it arrive in Florence?", "Does this train stop at Florence?", "Where is Florence?", "How much to Florence?"],
        correctAnswerIndex: 1,
        pronunciation: "KWES-to TRE-no si FER-ma a fi-REN-ze",
        explanation: "This helps confirm if the train stops at your desired destination.",
        explanationTranslation: "This helps confirm if the train stops at your desired destination.",
        audioPhrase: "Questo treno si ferma a Firenze?",
      ),
      const Question(
        id: 16,
        questionType: "Common Phrases - Cost",
        questionTypeTranslation: "Common Phrases - Cost",
        questionText: "How do you ask 'How much does it cost?'",
        questionTranslation: "How do you ask 'How much does it cost?'",
        options: ["Quanto costa?", "Che ore sono?", "Dove vai?", "Come stai?"],
        optionTranslations: ["How much does it cost?", "What time is it?", "Where are you going?", "How are you?"],
        correctAnswerIndex: 0,
        pronunciation: "KWAN-to COS-ta",
        explanation: "This essential phrase helps you ask about prices.",
        explanationTranslation: "This essential phrase helps you ask about prices.",
        audioPhrase: "Quanto costa?",
      ),
      const Question(
        id: 17,
        questionType: "Common Phrases - Seat Availability",
        questionTypeTranslation: "Common Phrases - Seat Availability",
        questionText: "How do you ask 'Is this seat free?'",
        questionTranslation: "How do you ask 'Is this seat free?'",
        options: ["Dov'è il mio posto?", "È libero questo posto?", "Posso prenotare?", "Quale carrozza?"],
        optionTranslations: ["Where is my seat?", "Is this seat free?", "Can I reserve?", "Which car?"],
        correctAnswerIndex: 1,
        pronunciation: "è LI-be-ro KWES-to POS-to",
        explanation: "Ask this before sitting down on the train.",
        explanationTranslation: "Ask this before sitting down on the train.",
        audioPhrase: "È libero questo posto?",
      ),
      const Question(
        id: 18,
        questionType: "Common Phrases - Seat Reservation",
        questionTypeTranslation: "Common Phrases - Seat Reservation",
        questionText: "How do you say 'I would like to reserve a seat'?",
        questionTranslation: "How do you say 'I would like to reserve a seat'?",
        options: ["Voglio un biglietto", "Vorrei prenotare un posto", "Ho un posto", "Cerco un treno"],
        optionTranslations: ["I want a ticket", "I would like to reserve a seat", "I have a seat", "I'm looking for a train"],
        correctAnswerIndex: 1,
        pronunciation: "vor-REI pre-no-TA-re un POS-to",
        explanation: "Use this phrase to request a seat reservation.",
        explanationTranslation: "Use this phrase to request a seat reservation.",
        audioPhrase: "Vorrei prenotare un posto",
      ),
      const Question(
        id: 19,
        questionType: "Basic Greetings - Hello",
        questionTypeTranslation: "Basic Greetings - Hello",
        questionText: "What does 'Buongiorno' mean?",
        questionTranslation: "What does 'Buongiorno' mean?",
        options: ["Good evening", "Good morning", "Goodbye", "Thank you"],
        optionTranslations: ["Buonasera", "Buongiorno", "Arrivederci", "Grazie"],
        correctAnswerIndex: 1,
        pronunciation: "bwon-JOR-no",
        explanation: "Buongiorno is a formal greeting used until afternoon.",
        explanationTranslation: "Buongiorno is a formal greeting used until afternoon.",
        audioPhrase: "Buongiorno",
      ),
      const Question(
        id: 20,
        questionType: "Basic Greetings - Goodbye",
        questionTypeTranslation: "Basic Greetings - Goodbye",
        questionText: "What does 'Arrivederci' mean?",
        questionTranslation: "What does 'Arrivederci' mean?",
        options: ["Hello", "Goodbye", "Please", "Excuse me"],
        optionTranslations: ["Ciao", "Arrivederci", "Per favore", "Scusi"],
        correctAnswerIndex: 1,
        pronunciation: "ar-ri-ve-DER-chi",
        explanation: "Arrivederci is a formal way to say goodbye.",
        explanationTranslation: "Arrivederci is a formal way to say goodbye.",
        audioPhrase: "Arrivederci",
      ),
    ];
  }

  // Backward compatibility
  List<Question> getQuestions() {
    return getItalianQuestions();
  }
}
